version: '2'
services:
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
      - ./front/product-manager
  db:
    image: postgres:13
    user: root
    environment:
      - POSTGRES_PASSWORD=spring
      - POSTGRES_USER=spring
      - POSTGRES_DB=spring
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
    links:
      - db
    ports:
      - "8080:8080"